In [1]:
import numpy as np

In [18]:
f=np.array([1,2,3,4,45.9])
s=np.array([90.3,54.2,89],dtype=str)
k=np.array(["50","2",12,43,50.5],dtype=int)
print(k)
print(f)
print(s)

[50  2 12 43 50]
[ 1.   2.   3.   4.  45.9]
['90.3' '54.2' '89']


In [22]:
#Zero Dimenshion Array
a=np.array(90)
print(a.ndim)
print(a)

0
90


In [25]:
#1-d Array
b=np.array([1,2,3,3])
print(b.ndim)
print(b)

1
[1 2 3 3]


In [31]:
#2-d Array
c=np.array([(1,2,3),(4,5,6),(7,8,9)])
print(c.ndim)
print(c)

2
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [39]:
#3-d Array
d=np.array([[
    [1,2],[3,4]],
    [[5,6],[7,8]
]])
print(d.ndim)
th=np.array([[
    [1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]
]])
print(th.ndim)

3
3


In [45]:
#acces element
i=np.array([1,2,3,4,5])
print(i[-2])
print(i[0:len(i):2])

4
[1 3 5]


In [92]:
j=np.array([[1,2,3,4],
            [5,6,7,8],
            [9,10,11,12]])
'''print(j[0])
print(j[0,2])
print(j[2,-1])
print(j[1,])
print(j[1,1:4])'''
print(j[0:2,0:2])
print(j[2,2])
print(j[0:])

[[1 2]
 [5 6]]
11


In [1]:
'''
----*
---**
--*** 
-****
*****
'''
n=10
for i in range(n):
    for j in range(1,n-i):
        print(" ",end="")
    for k in range(i+1):
        if k==0 or k==i:
            print("* ",end="")
        elif i==n-1:
            print("* ",end="")
        else:
            print("  ",end="")
    print()

         * 
        * * 
       *   * 
      *     * 
     *       * 
    *         * 
   *           * 
  *             * 
 *               * 
* * * * * * * * * * 


In [7]:
import numpy as np
td=np.array([[
    [1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]
]])
# print(td.ndim)
# print(td)
# print(td[1,0:,1:])
# print(td[0,0:,2:])
# print(td.shape)
for i in td:
    for j in i:
        for k in j:
            print(k,end=" ")
        print() 

1 2 3 
4 5 6 
7 8 9 
10 11 12 


In [8]:
for i in np.nditer(td):
    print(i,end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 

In [9]:
string="python"


0 p
1 y
2 t
3 h
4 o
5 n


In [20]:
#Convert 2d array into 1d array Using Flatten Function
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
new=a.flatten()
new[1]=300
print(a)
# print(a.ndim)
# print(new.ndim)
print(new)

b=np.array([[[1,2,3],
             [4,5,6]],
            [[7,8,9],[10,11,12]
    
]])
# print(b.ndim)
# print(b)
# new2=b.flatten()
# print(new2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[  1 300   3   4   5   6   7   8   9]


#Convert 2d array into 1d array Using ravel Function

In [18]:
c=np.array([[1,2,3],[4,5,6],[7,8,9]])
d=c.ravel()
d[1]=500
print(c)
print(d)

#if we make array using ravel fuction and change new array then previous array will be affected

[[  1 500   3]
 [  4   5   6]
 [  7   8   9]]
[  1 500   3   4   5   6   7   8   9]


In [24]:
#zeros
# zeroarray=np.zeros((5),dtype=int)
zeroarray=np.zeros(5)
print(zeroarray)

multi=np.zeros((3,2),dtype=int)
print(multi)

[0. 0. 0. 0. 0.]
[[0 0]
 [0 0]
 [0 0]]


In [28]:
#One
# np.ones((shape),dtype=float)
o=np.ones(5)
data=np.ones((4,3),dtype=str)
print(o)
print(data)

[1. 1. 1. 1. 1.]
[['1' '1' '1']
 ['1' '1' '1']
 ['1' '1' '1']
 ['1' '1' '1']]


In [34]:
#create array specific number using full() function
# arr_name=np.full(shape,value)
five=np.full((4,10),5)
print(five)

[[5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]]


In [41]:
#arange()
sk=np.arange(1,5)
print(sk)
# list(range(1,5))
sp=np.arange(1,10,3)
sp

[1 2 3 4]


array([1, 4, 7])

In [57]:
#eye
#it returns diagonal matrix here we give shape
e=np.eye(5,2,dtype=int)
print(e)

[[1 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]]


In [56]:
#identity
#it returns diagonal matrix here we can't give shape
j=np.identity(3,dtype=int)
print(j)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [73]:
#random function
#it return value in 0 to 1
r=np.random.rand(10)
s=np.random.rand(3,2)
# print(r)
for i in range(0,len(r)):
    print(i+1,r[i])

1 0.18208584929736815
2 0.23359236789568572
3 0.31970327389692177
4 0.6929575652726131
5 0.46042015932167624
6 0.8500502475829016
7 0.5133670796355013
8 0.8574839870616425
9 0.988332490798894
10 0.20558600922869863


In [80]:
h=np.random.randint(1,10,10)
print(h)
p=np.random.randint(0,10,size=(5,5))
# print(p)

[6 9 9 1 3 4 1 1 1 3]


In [10]:
#Create Dictionary
import numpy as np
import pandas as pd
dt={
    'zeros':np.zeros(10,dtype=int),
    'ones':np.ones((10),dtype=int),
    'full':np.full(10,4),
    'random':np.random.rand(10),
    'arange':np.arange(1,11),
    
}
df=pd.DataFrame(dt)
df

zeros  ones  full    random  arange
0      0     1     4  0.241944       1
1      0     1     4  0.071196       2
2      0     1     4  0.230853       3
3      0     1     4  0.237944       4
4      0     1     4  0.084399       5
5      0     1     4  0.867441       6
6      0     1     4  0.606749       7
7      0     1     4  0.926442       8
8      0     1     4  0.289308       9
9      0     1     4  0.883314      10